default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: bruno
  password:
  host: /var/run/postgresql

test:
  <<: *default
  database: blog_test
  username: bruno
  password:
  host: /var/run/postgresql

production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
